### PR TITLE
Feat bot settings

### PR DESCRIPTION
**Pull request by ccamisoss**
**Update styles and functionality across multiple sections to align with Figma designs**

This pull request introduces updates to ensure the site's styling and functionality adhere to the proposed Figma designs. The following changes have been implemented:

1. **Updated site font:**
   - Changed the font across the entire site to match the design specified in the Figma file.  
   *(Monday task link attached)*

2. **Refactored image upload input styles:**
   - Adjusted the styles and structure of the image upload inputs in both forms to align with the proposed design.  
   *(Monday task link attached)*

3. **Added missing `url` field in bot form:**
   - Included the `url` field in the bot creation form to collect the data required to activate a bot.  
   *(Monday task link attached)*

4. **Added download button in whitelist/blacklist sections:**
   - Developed the download button feature for both the whitelist and blacklist sections, enabling users to download the keyword list as proposed in the design.  
   *(Monday task link attached)*

5. **Aligned category item styles:**
   - Adjusted the width of elements in the category item to align with the coin item in the categories list. Also, corrected the capitalization of the title.  

6. **Improved keyword removal search behavior:**
   - Enhanced the functionality of the keyword removal search by ensuring that checked keywords remain visible in the list and are not filtered out when searching.  

---

**Technical details:**

- Refactored CSS and structure for input components.
- Modified form schemas and logic to include the new `url` field.
- Implemented functionality for downloading keyword lists as files.
- Adjusted alignment and capitalization styles in category list items.
- Updated keyword filtering logic to preserve checked items during searches.

### CODE REVIEW

**Comment by daviddflix** [comment]
Hey @ccamisoss everything is great, I tested the creation with the URL and it works as expected, however, there is an issue with the news creator tool.


image

**Comment by ccamisoss** [comment]
I'll push the fix in the following PR!

**Comment by ccamisoss** [comment]
the bug is fixed! @daviddflix

**Comment by ccamisoss** [comment]
I've added a few more changes: 
-added keyword filtering functionality in BotForm component
-add whitelist and blacklist keyword display in BotDetails component

**Comment by ccamisoss** [comment]
Suggestions applied! @daviddflix

**Review by fperedo — APPROVED** [review]

**Review by fperedo — APPROVED** [review]
@ccamisoss All bugs are fixed. Thanks! @daviddflix Please review.

**Comment by ccamisoss** [comment]
Added 1 more fix! 

-refactored filteredKeywordsFunction on keywordSettings component in order to place all checked keywords at the top of the list

Detail that I missed and was requested by Tamar. Monday task link: https://novatidelabs-company.monday.com/boards/1398916040/pulses/1719019873

@fperedo  @daviddflix

**Review by daviddflix — APPROVED** [review]

**Pull request merged**
