### PR TITLE
Feat/bot details view

### PR DESCRIPTION
**Pull request by ccamisoss**

### CODE REVIEW

**Comment by daviddflix** [comment]
## **Pull Request Feedback**

Error Message Display Issue:
The bot activation error message is not being displayed in the pop-up. We need to implement proper error handling and message display for activation failures
image


Timestamp Synchronization:
There's a discrepancy between development server and dashboard timestamps
The following fields need synchronization:

- Created At
- Updated At
- Next Run Time
image

**Comment by daviddflix** [comment]
Hey @ccamisoss the errors persist, let me know if the issue was solved

**Comment by ccamisoss** [comment]
Hey @daviddflix, I'll fix the errors and let you know!

**Comment by ccamisoss** [comment]
@daviddflix  I fixed the errors!

**Review by aialphanovatide — APPROVED** [review]

**Pull request merged**
