### PR TITLE
Refactor/update analysis section

### PR DESCRIPTION
**Pull request by ccamisoss**
**Add new services, refactor components, and improve functionality and styles**

This pull request introduces several updates and improvements to the AI Alpha Dashboard, focusing on creating new services, refactoring components for better modularity and error handling, and enhancing functionality and styles across the application. The following changes have been implemented:

---

#### **Services:**
1. **Created `sectionService`:**
   - Methods:
     - `getSections`: Fetches section data from the AI Alpha server.
     - `createSection`: Sends a request to create a new section.
     - `deleteSection`: Deletes a section.

2. **Created `contentCreation` service:**
   - Methods:
     - `getAnalyses`
     - `getCoinAnalysis`
     - `postAnalysis`
     - `deleteAnalysis`
     - `editAnalysis`
     - `createScheduleAnalysis`
     - `deleteScheduledAnalysis`
     - `getScheduledAnalyses`
   - All methods interact with the AI Alpha server's endpoints.

3. **Added `getCoins` method to `coinService` for fetching coin data.**

---

#### **Component Refactors:**
1. **`categoryDropdown`:**
   - Refactored to utilize `getCoins` from `coinService` instead of making direct fetch requests.

2. **`allAnalysis`:**
   - Refactored `handleSave` and `handleDelete` functions to use `editAnalysis` and `deleteAnalysis` methods from the `contentCreation` service, including the `section_id` parameter.
   - Improved error handling for these functions.

3. **`editModal`:**
   - Refactored `handleSave` to remove redundant code and accept the `section_id` parameter for article edits.

4. **`contentCreation`:**
   - Updated `handleSubmit` to include the `section_id` parameter and call `postAnalysis` from the `contentCreation` service.
   - Refactored `fetchAnalysis` to use the `getAnalyses` method, allowing for fetching data with optional `section_id` and `coin_id` parameters.
   - Created a `fetchSections` function to call `getSections` from the `sectionService`.
   - Added `useEffect` hooks for:
     - Fetching sections on component mount.
     - Fetching analysis when a section is selected.
   - Refactored `deleteScheduled`, `handleScheduleSave`, and `handleGetJobs` functions to use new service methods (`deleteScheduledAnalysis`, `createScheduleAnalysis`, `getScheduledAnalyses`) and improved error handling.

5. **`dropdownMenu`:**
   - Updated to use the `getCoins` method from `coinService` for fetching coin data.
   - Improved error handling.
   - Refactored to accept an `items` prop and fetch coins when `items` is null.

---

#### **Functional Changes:**
- Removed the `is top story` checkbox from the content creation form (to be implemented elsewhere).
- Added a loading state to the delete button in the `allAnalysis` item component.

---

#### **Styling Updates:**
- Improved the `item` component structure, updated the article image source, applied new styles, and set a default image.
- Enhanced styles for the `scheduledAnalysis` item.
- Fixed spinner alignment in the CoinGecko card on the home view.

---

#### **Clean-up:**
- Removed unused comments from the `scheduledJob` component.

---

### **Technical details:**
- Ensured all new service methods fetch data from the appropriate AI Alpha endpoints.
- Validated error handling for all refactored components and methods.
- Verified updated components integrate seamlessly with existing functionality.

Monday Task link: https://novatidelabs-company.monday.com/boards/1398916040/pulses/1634830106

### CODE REVIEW

**Comment by aialphanovatide** [comment]
Hey @ccamisoss good job with the organization and code quality.

The only suggestion is for this input, when I press over the input box the button is shown out of nowhere down below it.
image

**Comment by ccamisoss** [comment]
@daviddflix suggestions applied!

**Comment by ccamisoss** [comment]
Added a few more commits to fix the reported bugs on Monday:

- [Clear text area and date picker fields after new post is scheduled](https://novatidelabs-company.monday.com/boards/1398916040/pulses/1732256925)
- [Scheduled post identifier is added to the published content as a Title](https://novatidelabs-company.monday.com/boards/1398916040/pulses/1731030301)
- [Save button should be disable if content is empty](https://novatidelabs-company.monday.com/boards/1398916040/pulses/1731010926)
- [Required field error message is not displayed](https://novatidelabs-company.monday.com/boards/1398916040/pulses/1730987994)
- [Intermitent Undefined Error handling](https://novatidelabs-company.monday.com/boards/1398916040/pulses/1732145019)
- [User is not able to delete existing content](https://novatidelabs-company.monday.com/boards/1398916040/pulses/1731013860)
- [The edition modal cames with no content to be edited](https://novatidelabs-company.monday.com/boards/1398916040/pulses/1731007711)

@daviddflix @aialphanovatide

**Review by fperedo — COMMENTED** [review]
[Scheduled post identifier is added to the published content as a Title](https://novatidelabs-company.monday.com/boards/1398916040/pulses/1731030301)
[Save button should be disable if content is empty](https://novatidelabs-company.monday.com/boards/1398916040/pulses/1731010926)
[Required field error message is not displayed](https://novatidelabs-company.monday.com/boards/1398916040/pulses/1730987994)
[Intermitent Undefined Error handling](https://novatidelabs-company.monday.com/boards/1398916040/pulses/1732145019)

Bugs that still persist in the PR. @daviddflix @ccamisoss

**Review by fperedo — APPROVED** [review]
QA Approved, thanks @ccamisoss @daviddflix

**Pull request merged**
